### ISSUE TITLE
Remove / from parameter names

### ISSUE THREAD

**Issue by dawonn-haval** [ros2/geometry2#286]
https://github.com/ros2/geometry2/blob/7b0187f57d1d4f845601a774b609660af1dc92ba/tf2_ros/src/static_transform_broadcaster_node.cpp#L75

This may be to be unintentional, since it requires a param file to be written like this:
```yaml
velodyne_64_tf:
  ros__parameters:
    /translation/x: -0.003726033995784693
    /translation/y: 0.7164104007172224
    /translation/z: 1.595689449720807
    /rotation/x: 0.00977
    /rotation/y: -0.00704
    /rotation/z: 0.69892
    /rotation/w: 0.71472
    /frame_id: novatel
    /child_frame_id: velodyne64
```

I think at least removing the first / is a good plan. 

I _think_ that if the second / is replaced with a '.' it would enable a more common flow:
```yaml
velodyne_64_tf:
  ros__parameters:
    translation:
      x: -0.003726033995784693
      y: 0.7164104007172224
      z: 1.595689449720807
    rotation:
      x: 0.00977
      y: -0.00704
      z: 0.69892
      w: 0.71472
    frame_id: novatel
    child_frame_id: velodyne64
```
